#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 08:56:51 2018

@author: raulrodriguez
"""

print "this is carpentry"

cd

import pandas as pd

dat = pd.read_csv('data/gapminder_gdp_europe.csv, index_col = 'country')
